logging:
  level:
    root: warn
    org.mongodb.driver: warn
    org.springframework: info
    org.springframework.security: debug
    com.ico.api: debug

server:
  port: 8081
  ssl:
    enabled: false
  forward-headers-strategy: native
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

spring:
  profiles:
    active: prod # 기본 활성화 프로파일
    include:
      - db
      - mongodb
      - login