logging:
  level:
    root: warn
    org.mongodb.driver: warn
    org.springframework: info

server:
  port: 8082
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

spring:
  profiles:
    active: prod # 기본 활성화 프로파일
    include:
      - db
      - mongodb
      - login
